name: mmo_env
channels:
  - https://conda-dev.dev.schwab.com/conda/anaconda
  - https://conda-dev.dev.schwab.com/conda/opensource-approved
  - https://conda-dev.dev.schwab.com/conda/pending-opensource
  - nodefaults
dependencies:
  - python
  - Flask=1.0.3
  - Flask-Session=0.3.1
  - itsdangerous
  - jdcal
  - Jinja2
  - MarkupSafe
  - numpy=1.18.1
  - openpyxl
  - pandas=0.25.3
  - python-dateutil
  - pytz
  - scikit-learn=0.22.1
  - scipy=1.3.2
  - six
  - Werkzeug
  - Click
  - et_xmlfile
  - Xlrd
  - XlsxWriter
  - pymssql
